routes:
  # /register/: register
  /services/: services
  /contact/: contact
  /calendar/: calendar
  /: home

collections:
  /blog/:
    permalink: /blog/{slug}/
    filter: tag:blog

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
